### PR TITLE
Migrate to dotnet core 2.0

### PR DESCRIPTION
**Pull request by devvoid**
As of now, the project doesn't build on dotnet core 2.0 because the use of project.json is deprecated. This is just a simple `dotnet migrate` with the resulting build issues fixed. The test project runs now.

### CODE REVIEW

**Comment by lecode-official** [comment]
Hi devvoid,

thank you very much for your contribution. It looks good and I would accept the pull request. But I would really appreciate if you could add a `CONTRIBUTORS.md` to the root directory with the following content:

```md
# Contributors

This file contains a list of all people that have contributed to the project.

- devvoid
  * Migration to .NET Core 2.0
```

This is to make sure that you get the proper recognition for your contribution. If you want you can either add your real name or user name.

**Comment by devvoid** [comment]
Done.

Also, dotnet 2.0 no longer needs for you to explicitly call `dotnet restore` - every command that needs it runs it automatically. Should I go ahead and remove that from `README.md`?

**Comment by lecode-official** [comment]
Thanks,

you would do that, that would be nice. After that I will merge the pull request.

**Comment by devvoid** [comment]
I forgot, I already did that in a previous commit. Everything should be good for merge now

**Comment by lecode-official** [comment]
Thank you so much for your contribution. I will merge now.

**Pull request merged**
